//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XareuWFClient.PublicationServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publication", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.Publication")]
    [System.SerializableAttribute()]
    public partial class Publication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AnswersToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.PublicationServices.User AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float KarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NegativeVotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.PublicationServices.TagPlace PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositiveVotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AnswersTo {
            get {
                return this.AnswersToField;
            }
            set {
                if ((this.AnswersToField.Equals(value) != true)) {
                    this.AnswersToField = value;
                    this.RaisePropertyChanged("AnswersTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.PublicationServices.User Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDateTime {
            get {
                return this.CreationDateTimeField;
            }
            set {
                if ((this.CreationDateTimeField.Equals(value) != true)) {
                    this.CreationDateTimeField = value;
                    this.RaisePropertyChanged("CreationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsQuestion {
            get {
                return this.IsQuestionField;
            }
            set {
                if ((this.IsQuestionField.Equals(value) != true)) {
                    this.IsQuestionField = value;
                    this.RaisePropertyChanged("IsQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Karma {
            get {
                return this.KarmaField;
            }
            set {
                if ((this.KarmaField.Equals(value) != true)) {
                    this.KarmaField = value;
                    this.RaisePropertyChanged("Karma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NegativeVotes {
            get {
                return this.NegativeVotesField;
            }
            set {
                if ((this.NegativeVotesField.Equals(value) != true)) {
                    this.NegativeVotesField = value;
                    this.RaisePropertyChanged("NegativeVotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.PublicationServices.TagPlace Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositiveVotes {
            get {
                return this.PositiveVotesField;
            }
            set {
                if ((this.PositiveVotesField.Equals(value) != true)) {
                    this.PositiveVotesField = value;
                    this.RaisePropertyChanged("PositiveVotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.User")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.PublicationServices.TagPlace DefaultPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float KarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SignUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPictureURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.PublicationServices.TagPlace DefaultPlace {
            get {
                return this.DefaultPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultPlaceField, value) != true)) {
                    this.DefaultPlaceField = value;
                    this.RaisePropertyChanged("DefaultPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Karma {
            get {
                return this.KarmaField;
            }
            set {
                if ((this.KarmaField.Equals(value) != true)) {
                    this.KarmaField = value;
                    this.RaisePropertyChanged("Karma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nick {
            get {
                return this.NickField;
            }
            set {
                if ((object.ReferenceEquals(this.NickField, value) != true)) {
                    this.NickField = value;
                    this.RaisePropertyChanged("Nick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignUp {
            get {
                return this.SignUpField;
            }
            set {
                if ((this.SignUpField.Equals(value) != true)) {
                    this.SignUpField = value;
                    this.RaisePropertyChanged("SignUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPictureURL {
            get {
                return this.UserPictureURLField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPictureURLField, value) != true)) {
                    this.UserPictureURLField = value;
                    this.RaisePropertyChanged("UserPictureURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagPlace", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.TagPlace")]
    [System.SerializableAttribute()]
    public partial class TagPlace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublicationServices.IPublicationService")]
    public interface IPublicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicationService/GetAllPublications", ReplyAction="http://tempuri.org/IPublicationService/GetAllPublicationsResponse")]
        XareuWFClient.PublicationServices.Publication[] GetAllPublications(int number, int page, bool questions, bool publications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicationService/SearchPublicationWithText", ReplyAction="http://tempuri.org/IPublicationService/SearchPublicationWithTextResponse")]
        XareuWFClient.PublicationServices.Publication[] SearchPublicationWithText(out System.Guid newToken, long userID, System.Guid token, int number, int page, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicationService/GetPublication", ReplyAction="http://tempuri.org/IPublicationService/GetPublicationResponse")]
        XareuWFClient.PublicationServices.Publication GetPublication(long publicationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicationService/GetPublicationAnswers", ReplyAction="http://tempuri.org/IPublicationService/GetPublicationAnswersResponse")]
        XareuWFClient.PublicationServices.Publication[] GetPublicationAnswers(long publicationID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicationService/AddPublication", ReplyAction="http://tempuri.org/IPublicationService/AddPublicationResponse")]
        bool AddPublication(out System.Guid newToken, out long publicationID, long userID, System.Guid token, XareuWFClient.PublicationServices.Publication publication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicationService/EditPublication", ReplyAction="http://tempuri.org/IPublicationService/EditPublicationResponse")]
        bool EditPublication(out System.Guid newToken, long userID, System.Guid token, XareuWFClient.PublicationServices.Publication publication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicationService/GetUserPublications", ReplyAction="http://tempuri.org/IPublicationService/GetUserPublicationsResponse")]
        XareuWFClient.PublicationServices.Publication[] GetUserPublications(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page, bool questions, bool publications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicationService/GetPublicationsForUser", ReplyAction="http://tempuri.org/IPublicationService/GetPublicationsForUserResponse")]
        XareuWFClient.PublicationServices.Publication[] GetPublicationsForUser(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page, bool questions, bool publications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicationService/GetPublicationsForGroup", ReplyAction="http://tempuri.org/IPublicationService/GetPublicationsForGroupResponse")]
        XareuWFClient.PublicationServices.Publication[] GetPublicationsForGroup(out System.Guid newToken, long groupID, System.Guid token, long userAuthorID, int number, int page);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublicationServiceChannel : XareuWFClient.PublicationServices.IPublicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicationServiceClient : System.ServiceModel.ClientBase<XareuWFClient.PublicationServices.IPublicationService>, XareuWFClient.PublicationServices.IPublicationService {
        
        public PublicationServiceClient() {
        }
        
        public PublicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public XareuWFClient.PublicationServices.Publication[] GetAllPublications(int number, int page, bool questions, bool publications) {
            return base.Channel.GetAllPublications(number, page, questions, publications);
        }
        
        public XareuWFClient.PublicationServices.Publication[] SearchPublicationWithText(out System.Guid newToken, long userID, System.Guid token, int number, int page, string text) {
            return base.Channel.SearchPublicationWithText(out newToken, userID, token, number, page, text);
        }
        
        public XareuWFClient.PublicationServices.Publication GetPublication(long publicationID) {
            return base.Channel.GetPublication(publicationID);
        }
        
        public XareuWFClient.PublicationServices.Publication[] GetPublicationAnswers(long publicationID, int number, int page) {
            return base.Channel.GetPublicationAnswers(publicationID, number, page);
        }
        
        public bool AddPublication(out System.Guid newToken, out long publicationID, long userID, System.Guid token, XareuWFClient.PublicationServices.Publication publication) {
            return base.Channel.AddPublication(out newToken, out publicationID, userID, token, publication);
        }
        
        public bool EditPublication(out System.Guid newToken, long userID, System.Guid token, XareuWFClient.PublicationServices.Publication publication) {
            return base.Channel.EditPublication(out newToken, userID, token, publication);
        }
        
        public XareuWFClient.PublicationServices.Publication[] GetUserPublications(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page, bool questions, bool publications) {
            return base.Channel.GetUserPublications(out newToken, userID, token, userAuthorID, number, page, questions, publications);
        }
        
        public XareuWFClient.PublicationServices.Publication[] GetPublicationsForUser(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page, bool questions, bool publications) {
            return base.Channel.GetPublicationsForUser(out newToken, userID, token, userAuthorID, number, page, questions, publications);
        }
        
        public XareuWFClient.PublicationServices.Publication[] GetPublicationsForGroup(out System.Guid newToken, long groupID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetPublicationsForGroup(out newToken, groupID, token, userAuthorID, number, page);
        }
    }
}
