//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XareuWFClient.TagServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.Tag")]
    [System.SerializableAttribute()]
    public partial class Tag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publication", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.Publication")]
    [System.SerializableAttribute()]
    public partial class Publication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AnswersToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.TagServices.User AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float KarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NegativeVotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.TagServices.TagPlace PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositiveVotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AnswersTo {
            get {
                return this.AnswersToField;
            }
            set {
                if ((this.AnswersToField.Equals(value) != true)) {
                    this.AnswersToField = value;
                    this.RaisePropertyChanged("AnswersTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.TagServices.User Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDateTime {
            get {
                return this.CreationDateTimeField;
            }
            set {
                if ((this.CreationDateTimeField.Equals(value) != true)) {
                    this.CreationDateTimeField = value;
                    this.RaisePropertyChanged("CreationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsQuestion {
            get {
                return this.IsQuestionField;
            }
            set {
                if ((this.IsQuestionField.Equals(value) != true)) {
                    this.IsQuestionField = value;
                    this.RaisePropertyChanged("IsQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Karma {
            get {
                return this.KarmaField;
            }
            set {
                if ((this.KarmaField.Equals(value) != true)) {
                    this.KarmaField = value;
                    this.RaisePropertyChanged("Karma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NegativeVotes {
            get {
                return this.NegativeVotesField;
            }
            set {
                if ((this.NegativeVotesField.Equals(value) != true)) {
                    this.NegativeVotesField = value;
                    this.RaisePropertyChanged("NegativeVotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.TagServices.TagPlace Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositiveVotes {
            get {
                return this.PositiveVotesField;
            }
            set {
                if ((this.PositiveVotesField.Equals(value) != true)) {
                    this.PositiveVotesField = value;
                    this.RaisePropertyChanged("PositiveVotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.User")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.TagServices.TagPlace DefaultPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float KarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SignUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPictureURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.TagServices.TagPlace DefaultPlace {
            get {
                return this.DefaultPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultPlaceField, value) != true)) {
                    this.DefaultPlaceField = value;
                    this.RaisePropertyChanged("DefaultPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Karma {
            get {
                return this.KarmaField;
            }
            set {
                if ((this.KarmaField.Equals(value) != true)) {
                    this.KarmaField = value;
                    this.RaisePropertyChanged("Karma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nick {
            get {
                return this.NickField;
            }
            set {
                if ((object.ReferenceEquals(this.NickField, value) != true)) {
                    this.NickField = value;
                    this.RaisePropertyChanged("Nick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignUp {
            get {
                return this.SignUpField;
            }
            set {
                if ((this.SignUpField.Equals(value) != true)) {
                    this.SignUpField = value;
                    this.RaisePropertyChanged("SignUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPictureURL {
            get {
                return this.UserPictureURLField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPictureURLField, value) != true)) {
                    this.UserPictureURLField = value;
                    this.RaisePropertyChanged("UserPictureURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagPlace", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.TagPlace")]
    [System.SerializableAttribute()]
    public partial class TagPlace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TagServices.ITagService")]
    public interface ITagService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetTag", ReplyAction="http://tempuri.org/ITagService/GetTagResponse")]
        XareuWFClient.TagServices.Tag GetTag(long tagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetTagByName", ReplyAction="http://tempuri.org/ITagService/GetTagByNameResponse")]
        XareuWFClient.TagServices.Tag GetTagByName(string tagName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllTags", ReplyAction="http://tempuri.org/ITagService/GetAllTagsResponse")]
        XareuWFClient.TagServices.Tag[] GetAllTags(int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddTag", ReplyAction="http://tempuri.org/ITagService/AddTagResponse")]
        bool AddTag(out System.Guid newToken, out long tagID, long userID, System.Guid token, XareuWFClient.TagServices.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/DeleteTag", ReplyAction="http://tempuri.org/ITagService/DeleteTagResponse")]
        bool DeleteTag(out System.Guid newToken, long userID, System.Guid token, long tagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/EditTag", ReplyAction="http://tempuri.org/ITagService/EditTagResponse")]
        bool EditTag(out System.Guid newToken, long userID, System.Guid token, XareuWFClient.TagServices.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetTagsForPublication", ReplyAction="http://tempuri.org/ITagService/GetTagsForPublicationResponse")]
        XareuWFClient.TagServices.Tag[] GetTagsForPublication(long publicationID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetPublicationsWithTag", ReplyAction="http://tempuri.org/ITagService/GetPublicationsWithTagResponse")]
        XareuWFClient.TagServices.Publication[] GetPublicationsWithTag(long tagID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddTagToPublication", ReplyAction="http://tempuri.org/ITagService/AddTagToPublicationResponse")]
        bool AddTagToPublication(out System.Guid newToken, long userID, System.Guid token, long tagID, long publicationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/DeleteTagFromPublication", ReplyAction="http://tempuri.org/ITagService/DeleteTagFromPublicationResponse")]
        bool DeleteTagFromPublication(out System.Guid newToken, long userID, System.Guid token, long tagID, long publicationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllUserSubscriptions", ReplyAction="http://tempuri.org/ITagService/GetAllUserSubscriptionsResponse")]
        XareuWFClient.TagServices.Tag[] GetAllUserSubscriptions(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllUsersSubscribedToTag", ReplyAction="http://tempuri.org/ITagService/GetAllUsersSubscribedToTagResponse")]
        XareuWFClient.TagServices.User[] GetAllUsersSubscribedToTag(long tagID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddUserSubscription", ReplyAction="http://tempuri.org/ITagService/AddUserSubscriptionResponse")]
        bool AddUserSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long tagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/DeleteUserSubscription", ReplyAction="http://tempuri.org/ITagService/DeleteUserSubscriptionResponse")]
        bool DeleteUserSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long tagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/SearchTagsByText", ReplyAction="http://tempuri.org/ITagService/SearchTagsByTextResponse")]
        XareuWFClient.TagServices.Tag[] SearchTagsByText(string text, int number, int page);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITagServiceChannel : XareuWFClient.TagServices.ITagService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TagServiceClient : System.ServiceModel.ClientBase<XareuWFClient.TagServices.ITagService>, XareuWFClient.TagServices.ITagService {
        
        public TagServiceClient() {
        }
        
        public TagServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TagServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TagServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TagServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public XareuWFClient.TagServices.Tag GetTag(long tagID) {
            return base.Channel.GetTag(tagID);
        }
        
        public XareuWFClient.TagServices.Tag GetTagByName(string tagName) {
            return base.Channel.GetTagByName(tagName);
        }
        
        public XareuWFClient.TagServices.Tag[] GetAllTags(int number, int page) {
            return base.Channel.GetAllTags(number, page);
        }
        
        public bool AddTag(out System.Guid newToken, out long tagID, long userID, System.Guid token, XareuWFClient.TagServices.Tag tag) {
            return base.Channel.AddTag(out newToken, out tagID, userID, token, tag);
        }
        
        public bool DeleteTag(out System.Guid newToken, long userID, System.Guid token, long tagID) {
            return base.Channel.DeleteTag(out newToken, userID, token, tagID);
        }
        
        public bool EditTag(out System.Guid newToken, long userID, System.Guid token, XareuWFClient.TagServices.Tag tag) {
            return base.Channel.EditTag(out newToken, userID, token, tag);
        }
        
        public XareuWFClient.TagServices.Tag[] GetTagsForPublication(long publicationID, int number, int page) {
            return base.Channel.GetTagsForPublication(publicationID, number, page);
        }
        
        public XareuWFClient.TagServices.Publication[] GetPublicationsWithTag(long tagID, int number, int page) {
            return base.Channel.GetPublicationsWithTag(tagID, number, page);
        }
        
        public bool AddTagToPublication(out System.Guid newToken, long userID, System.Guid token, long tagID, long publicationID) {
            return base.Channel.AddTagToPublication(out newToken, userID, token, tagID, publicationID);
        }
        
        public bool DeleteTagFromPublication(out System.Guid newToken, long userID, System.Guid token, long tagID, long publicationID) {
            return base.Channel.DeleteTagFromPublication(out newToken, userID, token, tagID, publicationID);
        }
        
        public XareuWFClient.TagServices.Tag[] GetAllUserSubscriptions(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetAllUserSubscriptions(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public XareuWFClient.TagServices.User[] GetAllUsersSubscribedToTag(long tagID, int number, int page) {
            return base.Channel.GetAllUsersSubscribedToTag(tagID, number, page);
        }
        
        public bool AddUserSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long tagID) {
            return base.Channel.AddUserSubscription(out newToken, userID, token, userAuthorID, tagID);
        }
        
        public bool DeleteUserSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long tagID) {
            return base.Channel.DeleteUserSubscription(out newToken, userID, token, userAuthorID, tagID);
        }
        
        public XareuWFClient.TagServices.Tag[] SearchTagsByText(string text, int number, int page) {
            return base.Channel.SearchTagsByText(text, number, page);
        }
    }
}
