//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XareuWFClient.PlaceServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagPlace", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.TagPlace")]
    [System.SerializableAttribute()]
    public partial class TagPlace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publication", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.Publication")]
    [System.SerializableAttribute()]
    public partial class Publication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AnswersToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.PlaceServices.User AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float KarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NegativeVotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.PlaceServices.TagPlace PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositiveVotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AnswersTo {
            get {
                return this.AnswersToField;
            }
            set {
                if ((this.AnswersToField.Equals(value) != true)) {
                    this.AnswersToField = value;
                    this.RaisePropertyChanged("AnswersTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.PlaceServices.User Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDateTime {
            get {
                return this.CreationDateTimeField;
            }
            set {
                if ((this.CreationDateTimeField.Equals(value) != true)) {
                    this.CreationDateTimeField = value;
                    this.RaisePropertyChanged("CreationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsQuestion {
            get {
                return this.IsQuestionField;
            }
            set {
                if ((this.IsQuestionField.Equals(value) != true)) {
                    this.IsQuestionField = value;
                    this.RaisePropertyChanged("IsQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Karma {
            get {
                return this.KarmaField;
            }
            set {
                if ((this.KarmaField.Equals(value) != true)) {
                    this.KarmaField = value;
                    this.RaisePropertyChanged("Karma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NegativeVotes {
            get {
                return this.NegativeVotesField;
            }
            set {
                if ((this.NegativeVotesField.Equals(value) != true)) {
                    this.NegativeVotesField = value;
                    this.RaisePropertyChanged("NegativeVotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.PlaceServices.TagPlace Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositiveVotes {
            get {
                return this.PositiveVotesField;
            }
            set {
                if ((this.PositiveVotesField.Equals(value) != true)) {
                    this.PositiveVotesField = value;
                    this.RaisePropertyChanged("PositiveVotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.User")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.PlaceServices.TagPlace DefaultPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float KarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SignUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPictureURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.PlaceServices.TagPlace DefaultPlace {
            get {
                return this.DefaultPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultPlaceField, value) != true)) {
                    this.DefaultPlaceField = value;
                    this.RaisePropertyChanged("DefaultPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Karma {
            get {
                return this.KarmaField;
            }
            set {
                if ((this.KarmaField.Equals(value) != true)) {
                    this.KarmaField = value;
                    this.RaisePropertyChanged("Karma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nick {
            get {
                return this.NickField;
            }
            set {
                if ((object.ReferenceEquals(this.NickField, value) != true)) {
                    this.NickField = value;
                    this.RaisePropertyChanged("Nick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignUp {
            get {
                return this.SignUpField;
            }
            set {
                if ((this.SignUpField.Equals(value) != true)) {
                    this.SignUpField = value;
                    this.RaisePropertyChanged("SignUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPictureURL {
            get {
                return this.UserPictureURLField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPictureURLField, value) != true)) {
                    this.UserPictureURLField = value;
                    this.RaisePropertyChanged("UserPictureURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlaceServices.IPlaceService")]
    public interface IPlaceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/GetTagPlace", ReplyAction="http://tempuri.org/IPlaceService/GetTagPlaceResponse")]
        XareuWFClient.PlaceServices.TagPlace GetTagPlace(long tagPlaceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/AddTagPlace", ReplyAction="http://tempuri.org/IPlaceService/AddTagPlaceResponse")]
        bool AddTagPlace(out System.Guid newToken, long userID, System.Guid token, XareuWFClient.PlaceServices.TagPlace tagPlace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/GetSons", ReplyAction="http://tempuri.org/IPlaceService/GetSonsResponse")]
        XareuWFClient.PlaceServices.TagPlace[] GetSons(long tagPlaceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/GetPlaceTagsInPublication", ReplyAction="http://tempuri.org/IPlaceService/GetPlaceTagsInPublicationResponse")]
        XareuWFClient.PlaceServices.TagPlace[] GetPlaceTagsInPublication(long publicationID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/GetPublicationForPlaceTag", ReplyAction="http://tempuri.org/IPlaceService/GetPublicationForPlaceTagResponse")]
        XareuWFClient.PlaceServices.Publication[] GetPublicationForPlaceTag(long placeTagID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/AddPlaceTagInPublication", ReplyAction="http://tempuri.org/IPlaceService/AddPlaceTagInPublicationResponse")]
        bool AddPlaceTagInPublication(out System.Guid newToken, long userID, System.Guid token, long publicationID, long placeTagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/DeletePlaceTagInPublication", ReplyAction="http://tempuri.org/IPlaceService/DeletePlaceTagInPublicationResponse")]
        bool DeletePlaceTagInPublication(out System.Guid newToken, long userID, System.Guid token, long publicationID, long placeTagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/GetUserPlaceTagSubscription", ReplyAction="http://tempuri.org/IPlaceService/GetUserPlaceTagSubscriptionResponse")]
        XareuWFClient.PlaceServices.TagPlace[] GetUserPlaceTagSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/GetUsersSubscribedToPlaceTag", ReplyAction="http://tempuri.org/IPlaceService/GetUsersSubscribedToPlaceTagResponse")]
        XareuWFClient.PlaceServices.User[] GetUsersSubscribedToPlaceTag(long placeTag, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/AddUserSubscription", ReplyAction="http://tempuri.org/IPlaceService/AddUserSubscriptionResponse")]
        bool AddUserSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long placeTagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaceService/DeleteUserSubscription", ReplyAction="http://tempuri.org/IPlaceService/DeleteUserSubscriptionResponse")]
        bool DeleteUserSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long placeTagID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlaceServiceChannel : XareuWFClient.PlaceServices.IPlaceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlaceServiceClient : System.ServiceModel.ClientBase<XareuWFClient.PlaceServices.IPlaceService>, XareuWFClient.PlaceServices.IPlaceService {
        
        public PlaceServiceClient() {
        }
        
        public PlaceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlaceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlaceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlaceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public XareuWFClient.PlaceServices.TagPlace GetTagPlace(long tagPlaceID) {
            return base.Channel.GetTagPlace(tagPlaceID);
        }
        
        public bool AddTagPlace(out System.Guid newToken, long userID, System.Guid token, XareuWFClient.PlaceServices.TagPlace tagPlace) {
            return base.Channel.AddTagPlace(out newToken, userID, token, tagPlace);
        }
        
        public XareuWFClient.PlaceServices.TagPlace[] GetSons(long tagPlaceID) {
            return base.Channel.GetSons(tagPlaceID);
        }
        
        public XareuWFClient.PlaceServices.TagPlace[] GetPlaceTagsInPublication(long publicationID, int number, int page) {
            return base.Channel.GetPlaceTagsInPublication(publicationID, number, page);
        }
        
        public XareuWFClient.PlaceServices.Publication[] GetPublicationForPlaceTag(long placeTagID, int number, int page) {
            return base.Channel.GetPublicationForPlaceTag(placeTagID, number, page);
        }
        
        public bool AddPlaceTagInPublication(out System.Guid newToken, long userID, System.Guid token, long publicationID, long placeTagID) {
            return base.Channel.AddPlaceTagInPublication(out newToken, userID, token, publicationID, placeTagID);
        }
        
        public bool DeletePlaceTagInPublication(out System.Guid newToken, long userID, System.Guid token, long publicationID, long placeTagID) {
            return base.Channel.DeletePlaceTagInPublication(out newToken, userID, token, publicationID, placeTagID);
        }
        
        public XareuWFClient.PlaceServices.TagPlace[] GetUserPlaceTagSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetUserPlaceTagSubscription(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public XareuWFClient.PlaceServices.User[] GetUsersSubscribedToPlaceTag(long placeTag, int number, int page) {
            return base.Channel.GetUsersSubscribedToPlaceTag(placeTag, number, page);
        }
        
        public bool AddUserSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long placeTagID) {
            return base.Channel.AddUserSubscription(out newToken, userID, token, userAuthorID, placeTagID);
        }
        
        public bool DeleteUserSubscription(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long placeTagID) {
            return base.Channel.DeleteUserSubscription(out newToken, userID, token, userAuthorID, placeTagID);
        }
    }
}
