//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XareuWFClient.GroupServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.Group")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.GroupServices.User OwnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Creation {
            get {
                return this.CreationField;
            }
            set {
                if ((this.CreationField.Equals(value) != true)) {
                    this.CreationField = value;
                    this.RaisePropertyChanged("Creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.GroupServices.User Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.User")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.GroupServices.TagPlace DefaultPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float KarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SignUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPictureURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.GroupServices.TagPlace DefaultPlace {
            get {
                return this.DefaultPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultPlaceField, value) != true)) {
                    this.DefaultPlaceField = value;
                    this.RaisePropertyChanged("DefaultPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Karma {
            get {
                return this.KarmaField;
            }
            set {
                if ((this.KarmaField.Equals(value) != true)) {
                    this.KarmaField = value;
                    this.RaisePropertyChanged("Karma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nick {
            get {
                return this.NickField;
            }
            set {
                if ((object.ReferenceEquals(this.NickField, value) != true)) {
                    this.NickField = value;
                    this.RaisePropertyChanged("Nick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignUp {
            get {
                return this.SignUpField;
            }
            set {
                if ((this.SignUpField.Equals(value) != true)) {
                    this.SignUpField = value;
                    this.RaisePropertyChanged("SignUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPictureURL {
            get {
                return this.UserPictureURLField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPictureURLField, value) != true)) {
                    this.UserPictureURLField = value;
                    this.RaisePropertyChanged("UserPictureURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagPlace", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.TagPlace")]
    [System.SerializableAttribute()]
    public partial class TagPlace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupJoinRequest", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.Group")]
    [System.SerializableAttribute()]
    public partial class GroupJoinRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.GroupServices.Group GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.GroupServices.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.GroupServices.Group Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.GroupServices.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupUsers", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.Group")]
    [System.SerializableAttribute()]
    public partial class GroupUsers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.GroupServices.Group GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.GroupServices.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.GroupServices.Group Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.GroupServices.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GroupServices.IGroupService")]
    public interface IGroupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetGroupById", ReplyAction="http://tempuri.org/IGroupService/GetGroupByIdResponse")]
        XareuWFClient.GroupServices.Group GetGroupById(long groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetGroupByName", ReplyAction="http://tempuri.org/IGroupService/GetGroupByNameResponse")]
        XareuWFClient.GroupServices.Group GetGroupByName(string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetAllGroups", ReplyAction="http://tempuri.org/IGroupService/GetAllGroupsResponse")]
        XareuWFClient.GroupServices.Group[] GetAllGroups(int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetUserOwnGroups", ReplyAction="http://tempuri.org/IGroupService/GetUserOwnGroupsResponse")]
        XareuWFClient.GroupServices.Group[] GetUserOwnGroups(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/CreateGroup", ReplyAction="http://tempuri.org/IGroupService/CreateGroupResponse")]
        bool CreateGroup(out System.Guid newToken, long userID, System.Guid token, string name, long userAuthorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/DeleteGroup", ReplyAction="http://tempuri.org/IGroupService/DeleteGroupResponse")]
        bool DeleteGroup(out System.Guid newToken, long userID, System.Guid token, long groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/SetGroupPrivacy", ReplyAction="http://tempuri.org/IGroupService/SetGroupPrivacyResponse")]
        bool SetGroupPrivacy(out System.Guid newToken, long userID, System.Guid token, long groupID, bool isPrivate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetGroupsInPublication", ReplyAction="http://tempuri.org/IGroupService/GetGroupsInPublicationResponse")]
        XareuWFClient.GroupServices.Group[] GetGroupsInPublication(long publicationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/AddGroupToPublication", ReplyAction="http://tempuri.org/IGroupService/AddGroupToPublicationResponse")]
        bool AddGroupToPublication(out System.Guid newToken, long userID, System.Guid token, long publicationID, long groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/DeleteGroupFromPublication", ReplyAction="http://tempuri.org/IGroupService/DeleteGroupFromPublicationResponse")]
        bool DeleteGroupFromPublication(out System.Guid newToken, long userID, System.Guid token, long publicationID, long groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetGroupJoinRequest", ReplyAction="http://tempuri.org/IGroupService/GetGroupJoinRequestResponse")]
        XareuWFClient.GroupServices.GroupJoinRequest GetGroupJoinRequest(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetGroupJoinRequests", ReplyAction="http://tempuri.org/IGroupService/GetGroupJoinRequestsResponse")]
        XareuWFClient.GroupServices.GroupJoinRequest[] GetGroupJoinRequests(out System.Guid newToken, long userID, System.Guid token, long groupID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetUserJoinRequests", ReplyAction="http://tempuri.org/IGroupService/GetUserJoinRequestsResponse")]
        XareuWFClient.GroupServices.GroupJoinRequest[] GetUserJoinRequests(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/AddJoinRequest", ReplyAction="http://tempuri.org/IGroupService/AddJoinRequestResponse")]
        bool AddJoinRequest(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/DeleteJoinRequest", ReplyAction="http://tempuri.org/IGroupService/DeleteJoinRequestResponse")]
        bool DeleteJoinRequest(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetSubscribedUsers", ReplyAction="http://tempuri.org/IGroupService/GetSubscribedUsersResponse")]
        XareuWFClient.GroupServices.GroupUsers[] GetSubscribedUsers(out System.Guid newToken, long userID, System.Guid token, long groupID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetUserSubscriptions", ReplyAction="http://tempuri.org/IGroupService/GetUserSubscriptionsResponse")]
        XareuWFClient.GroupServices.GroupUsers[] GetUserSubscriptions(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/AddSubscription", ReplyAction="http://tempuri.org/IGroupService/AddSubscriptionResponse")]
        bool AddSubscription(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/DeleteSubscription", ReplyAction="http://tempuri.org/IGroupService/DeleteSubscriptionResponse")]
        bool DeleteSubscription(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/SearchGroupsByName", ReplyAction="http://tempuri.org/IGroupService/SearchGroupsByNameResponse")]
        XareuWFClient.GroupServices.Group[] SearchGroupsByName(string name, int number, int page);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGroupServiceChannel : XareuWFClient.GroupServices.IGroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupServiceClient : System.ServiceModel.ClientBase<XareuWFClient.GroupServices.IGroupService>, XareuWFClient.GroupServices.IGroupService {
        
        public GroupServiceClient() {
        }
        
        public GroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public XareuWFClient.GroupServices.Group GetGroupById(long groupID) {
            return base.Channel.GetGroupById(groupID);
        }
        
        public XareuWFClient.GroupServices.Group GetGroupByName(string groupName) {
            return base.Channel.GetGroupByName(groupName);
        }
        
        public XareuWFClient.GroupServices.Group[] GetAllGroups(int number, int page) {
            return base.Channel.GetAllGroups(number, page);
        }
        
        public XareuWFClient.GroupServices.Group[] GetUserOwnGroups(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetUserOwnGroups(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public bool CreateGroup(out System.Guid newToken, long userID, System.Guid token, string name, long userAuthorID) {
            return base.Channel.CreateGroup(out newToken, userID, token, name, userAuthorID);
        }
        
        public bool DeleteGroup(out System.Guid newToken, long userID, System.Guid token, long groupID) {
            return base.Channel.DeleteGroup(out newToken, userID, token, groupID);
        }
        
        public bool SetGroupPrivacy(out System.Guid newToken, long userID, System.Guid token, long groupID, bool isPrivate) {
            return base.Channel.SetGroupPrivacy(out newToken, userID, token, groupID, isPrivate);
        }
        
        public XareuWFClient.GroupServices.Group[] GetGroupsInPublication(long publicationID) {
            return base.Channel.GetGroupsInPublication(publicationID);
        }
        
        public bool AddGroupToPublication(out System.Guid newToken, long userID, System.Guid token, long publicationID, long groupID) {
            return base.Channel.AddGroupToPublication(out newToken, userID, token, publicationID, groupID);
        }
        
        public bool DeleteGroupFromPublication(out System.Guid newToken, long userID, System.Guid token, long publicationID, long groupID) {
            return base.Channel.DeleteGroupFromPublication(out newToken, userID, token, publicationID, groupID);
        }
        
        public XareuWFClient.GroupServices.GroupJoinRequest GetGroupJoinRequest(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID) {
            return base.Channel.GetGroupJoinRequest(out newToken, userID, token, groupID, userAuthorID);
        }
        
        public XareuWFClient.GroupServices.GroupJoinRequest[] GetGroupJoinRequests(out System.Guid newToken, long userID, System.Guid token, long groupID, int number, int page) {
            return base.Channel.GetGroupJoinRequests(out newToken, userID, token, groupID, number, page);
        }
        
        public XareuWFClient.GroupServices.GroupJoinRequest[] GetUserJoinRequests(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetUserJoinRequests(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public bool AddJoinRequest(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID) {
            return base.Channel.AddJoinRequest(out newToken, userID, token, groupID, userAuthorID);
        }
        
        public bool DeleteJoinRequest(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID) {
            return base.Channel.DeleteJoinRequest(out newToken, userID, token, groupID, userAuthorID);
        }
        
        public XareuWFClient.GroupServices.GroupUsers[] GetSubscribedUsers(out System.Guid newToken, long userID, System.Guid token, long groupID, int number, int page) {
            return base.Channel.GetSubscribedUsers(out newToken, userID, token, groupID, number, page);
        }
        
        public XareuWFClient.GroupServices.GroupUsers[] GetUserSubscriptions(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetUserSubscriptions(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public bool AddSubscription(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID) {
            return base.Channel.AddSubscription(out newToken, userID, token, groupID, userAuthorID);
        }
        
        public bool DeleteSubscription(out System.Guid newToken, long userID, System.Guid token, long groupID, long userAuthorID) {
            return base.Channel.DeleteSubscription(out newToken, userID, token, groupID, userAuthorID);
        }
        
        public XareuWFClient.GroupServices.Group[] SearchGroupsByName(string name, int number, int page) {
            return base.Channel.SearchGroupsByName(name, number, page);
        }
    }
}
