//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XareuWFClient.UserServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.User")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.UserServices.TagPlace DefaultPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float KarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SignUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPictureURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.UserServices.TagPlace DefaultPlace {
            get {
                return this.DefaultPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultPlaceField, value) != true)) {
                    this.DefaultPlaceField = value;
                    this.RaisePropertyChanged("DefaultPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Karma {
            get {
                return this.KarmaField;
            }
            set {
                if ((this.KarmaField.Equals(value) != true)) {
                    this.KarmaField = value;
                    this.RaisePropertyChanged("Karma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nick {
            get {
                return this.NickField;
            }
            set {
                if ((object.ReferenceEquals(this.NickField, value) != true)) {
                    this.NickField = value;
                    this.RaisePropertyChanged("Nick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignUp {
            get {
                return this.SignUpField;
            }
            set {
                if ((this.SignUpField.Equals(value) != true)) {
                    this.SignUpField = value;
                    this.RaisePropertyChanged("SignUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPictureURL {
            get {
                return this.UserPictureURLField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPictureURLField, value) != true)) {
                    this.UserPictureURLField = value;
                    this.RaisePropertyChanged("UserPictureURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagPlace", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.TagPlace")]
    [System.SerializableAttribute()]
    public partial class TagPlace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFollow", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.UserFollow")]
    [System.SerializableAttribute()]
    public partial class UserFollow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.UserServices.User UserFollowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.UserServices.User UserFollowingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.UserServices.User UserFollowed {
            get {
                return this.UserFollowedField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFollowedField, value) != true)) {
                    this.UserFollowedField = value;
                    this.RaisePropertyChanged("UserFollowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.UserServices.User UserFollowing {
            get {
                return this.UserFollowingField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFollowingField, value) != true)) {
                    this.UserFollowingField = value;
                    this.RaisePropertyChanged("UserFollowing");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFollowRequest", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.UserFollow")]
    [System.SerializableAttribute()]
    public partial class UserFollowRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.UserServices.User UserFollowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.UserServices.User UserFollowerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.UserServices.User UserFollowed {
            get {
                return this.UserFollowedField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFollowedField, value) != true)) {
                    this.UserFollowedField = value;
                    this.RaisePropertyChanged("UserFollowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.UserServices.User UserFollower {
            get {
                return this.UserFollowerField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFollowerField, value) != true)) {
                    this.UserFollowerField = value;
                    this.RaisePropertyChanged("UserFollower");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publication", Namespace="http://schemas.datacontract.org/2004/07/XareuServices.Model.Publication")]
    [System.SerializableAttribute()]
    public partial class Publication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AnswersToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.UserServices.User AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float KarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NegativeVotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XareuWFClient.UserServices.TagPlace PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositiveVotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AnswersTo {
            get {
                return this.AnswersToField;
            }
            set {
                if ((this.AnswersToField.Equals(value) != true)) {
                    this.AnswersToField = value;
                    this.RaisePropertyChanged("AnswersTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.UserServices.User Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDateTime {
            get {
                return this.CreationDateTimeField;
            }
            set {
                if ((this.CreationDateTimeField.Equals(value) != true)) {
                    this.CreationDateTimeField = value;
                    this.RaisePropertyChanged("CreationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsQuestion {
            get {
                return this.IsQuestionField;
            }
            set {
                if ((this.IsQuestionField.Equals(value) != true)) {
                    this.IsQuestionField = value;
                    this.RaisePropertyChanged("IsQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Karma {
            get {
                return this.KarmaField;
            }
            set {
                if ((this.KarmaField.Equals(value) != true)) {
                    this.KarmaField = value;
                    this.RaisePropertyChanged("Karma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NegativeVotes {
            get {
                return this.NegativeVotesField;
            }
            set {
                if ((this.NegativeVotesField.Equals(value) != true)) {
                    this.NegativeVotesField = value;
                    this.RaisePropertyChanged("NegativeVotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XareuWFClient.UserServices.TagPlace Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositiveVotes {
            get {
                return this.PositiveVotesField;
            }
            set {
                if ((this.PositiveVotesField.Equals(value) != true)) {
                    this.PositiveVotesField = value;
                    this.RaisePropertyChanged("PositiveVotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServices.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterNewUser", ReplyAction="http://tempuri.org/IUserService/RegisterNewUserResponse")]
        bool RegisterNewUser(string nick, string email, string password, long defaultPlaceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        bool DeleteUser(out System.Guid newToken, long userID, System.Guid token, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByID", ReplyAction="http://tempuri.org/IUserService/GetUserByIDResponse")]
        XareuWFClient.UserServices.User GetUserByID(long userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByNick", ReplyAction="http://tempuri.org/IUserService/GetUserByNickResponse")]
        XareuWFClient.UserServices.User GetUserByNick(string nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByEmail", ReplyAction="http://tempuri.org/IUserService/GetUserByEmailResponse")]
        XareuWFClient.UserServices.User GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditUser", ReplyAction="http://tempuri.org/IUserService/EditUserResponse")]
        bool EditUser(out System.Guid newToken, long userID, System.Guid token, XareuWFClient.UserServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetRegisteredUsers", ReplyAction="http://tempuri.org/IUserService/GetRegisteredUsersResponse")]
        XareuWFClient.UserServices.User[] GetRegisteredUsers(int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchUsersByName", ReplyAction="http://tempuri.org/IUserService/SearchUsersByNameResponse")]
        XareuWFClient.UserServices.User[] SearchUsersByName(string name, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchUsersByKarma", ReplyAction="http://tempuri.org/IUserService/SearchUsersByKarmaResponse")]
        XareuWFClient.UserServices.User[] SearchUsersByKarma(float karma, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchUsersByEmail", ReplyAction="http://tempuri.org/IUserService/SearchUsersByEmailResponse")]
        XareuWFClient.UserServices.User[] SearchUsersByEmail(string email, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchUsersByTagPlace", ReplyAction="http://tempuri.org/IUserService/SearchUsersByTagPlaceResponse")]
        XareuWFClient.UserServices.User[] SearchUsersByTagPlace(long tagPlaceID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserFollow", ReplyAction="http://tempuri.org/IUserService/GetUserFollowResponse")]
        XareuWFClient.UserServices.UserFollow GetUserFollow(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userFollowedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserFollowers", ReplyAction="http://tempuri.org/IUserService/GetUserFollowersResponse")]
        XareuWFClient.UserServices.UserFollow[] GetUserFollowers(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserOwnFollows", ReplyAction="http://tempuri.org/IUserService/GetUserOwnFollowsResponse")]
        XareuWFClient.UserServices.UserFollow[] GetUserOwnFollows(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUserFollow", ReplyAction="http://tempuri.org/IUserService/AddUserFollowResponse")]
        bool AddUserFollow(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userFollowedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUserFollow", ReplyAction="http://tempuri.org/IUserService/DeleteUserFollowResponse")]
        bool DeleteUserFollow(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userFollowedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserFollowRequest", ReplyAction="http://tempuri.org/IUserService/GetUserFollowRequestResponse")]
        XareuWFClient.UserServices.UserFollowRequest GetUserFollowRequest(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userRequestedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserFollowRequests", ReplyAction="http://tempuri.org/IUserService/GetUserFollowRequestsResponse")]
        XareuWFClient.UserServices.UserFollowRequest[] GetUserFollowRequests(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserOwnFollowRequests", ReplyAction="http://tempuri.org/IUserService/GetUserOwnFollowRequestsResponse")]
        XareuWFClient.UserServices.UserFollowRequest[] GetUserOwnFollowRequests(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUserFollowRequest", ReplyAction="http://tempuri.org/IUserService/AddUserFollowRequestResponse")]
        bool AddUserFollowRequest(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userRequestedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUserFollowRequest", ReplyAction="http://tempuri.org/IUserService/DeleteUserFollowRequestResponse")]
        bool DeleteUserFollowRequest(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userRequestedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UsersInPublication", ReplyAction="http://tempuri.org/IUserService/UsersInPublicationResponse")]
        XareuWFClient.UserServices.User[] UsersInPublication(long publicationID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UserMentions", ReplyAction="http://tempuri.org/IUserService/UserMentionsResponse")]
        XareuWFClient.UserServices.Publication[] UserMentions(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUserInPublication", ReplyAction="http://tempuri.org/IUserService/AddUserInPublicationResponse")]
        bool AddUserInPublication(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int publicationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUserFromPublication", ReplyAction="http://tempuri.org/IUserService/DeleteUserFromPublicationResponse")]
        bool DeleteUserFromPublication(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int publicationID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : XareuWFClient.UserServices.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<XareuWFClient.UserServices.IUserService>, XareuWFClient.UserServices.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterNewUser(string nick, string email, string password, long defaultPlaceID) {
            return base.Channel.RegisterNewUser(nick, email, password, defaultPlaceID);
        }
        
        public bool DeleteUser(out System.Guid newToken, long userID, System.Guid token, string email, string password) {
            return base.Channel.DeleteUser(out newToken, userID, token, email, password);
        }
        
        public XareuWFClient.UserServices.User GetUserByID(long userID) {
            return base.Channel.GetUserByID(userID);
        }
        
        public XareuWFClient.UserServices.User GetUserByNick(string nick) {
            return base.Channel.GetUserByNick(nick);
        }
        
        public XareuWFClient.UserServices.User GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public bool EditUser(out System.Guid newToken, long userID, System.Guid token, XareuWFClient.UserServices.User user) {
            return base.Channel.EditUser(out newToken, userID, token, user);
        }
        
        public XareuWFClient.UserServices.User[] GetRegisteredUsers(int number, int page) {
            return base.Channel.GetRegisteredUsers(number, page);
        }
        
        public XareuWFClient.UserServices.User[] SearchUsersByName(string name, int number, int page) {
            return base.Channel.SearchUsersByName(name, number, page);
        }
        
        public XareuWFClient.UserServices.User[] SearchUsersByKarma(float karma, int number, int page) {
            return base.Channel.SearchUsersByKarma(karma, number, page);
        }
        
        public XareuWFClient.UserServices.User[] SearchUsersByEmail(string email, int number, int page) {
            return base.Channel.SearchUsersByEmail(email, number, page);
        }
        
        public XareuWFClient.UserServices.User[] SearchUsersByTagPlace(long tagPlaceID, int number, int page) {
            return base.Channel.SearchUsersByTagPlace(tagPlaceID, number, page);
        }
        
        public XareuWFClient.UserServices.UserFollow GetUserFollow(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userFollowedID) {
            return base.Channel.GetUserFollow(out newToken, userID, token, userAuthorID, userFollowedID);
        }
        
        public XareuWFClient.UserServices.UserFollow[] GetUserFollowers(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetUserFollowers(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public XareuWFClient.UserServices.UserFollow[] GetUserOwnFollows(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetUserOwnFollows(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public bool AddUserFollow(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userFollowedID) {
            return base.Channel.AddUserFollow(out newToken, userID, token, userAuthorID, userFollowedID);
        }
        
        public bool DeleteUserFollow(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userFollowedID) {
            return base.Channel.DeleteUserFollow(out newToken, userID, token, userAuthorID, userFollowedID);
        }
        
        public XareuWFClient.UserServices.UserFollowRequest GetUserFollowRequest(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userRequestedID) {
            return base.Channel.GetUserFollowRequest(out newToken, userID, token, userAuthorID, userRequestedID);
        }
        
        public XareuWFClient.UserServices.UserFollowRequest[] GetUserFollowRequests(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetUserFollowRequests(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public XareuWFClient.UserServices.UserFollowRequest[] GetUserOwnFollowRequests(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.GetUserOwnFollowRequests(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public bool AddUserFollowRequest(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userRequestedID) {
            return base.Channel.AddUserFollowRequest(out newToken, userID, token, userAuthorID, userRequestedID);
        }
        
        public bool DeleteUserFollowRequest(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, long userRequestedID) {
            return base.Channel.DeleteUserFollowRequest(out newToken, userID, token, userAuthorID, userRequestedID);
        }
        
        public XareuWFClient.UserServices.User[] UsersInPublication(long publicationID, int number, int page) {
            return base.Channel.UsersInPublication(publicationID, number, page);
        }
        
        public XareuWFClient.UserServices.Publication[] UserMentions(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int number, int page) {
            return base.Channel.UserMentions(out newToken, userID, token, userAuthorID, number, page);
        }
        
        public bool AddUserInPublication(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int publicationID) {
            return base.Channel.AddUserInPublication(out newToken, userID, token, userAuthorID, publicationID);
        }
        
        public bool DeleteUserFromPublication(out System.Guid newToken, long userID, System.Guid token, long userAuthorID, int publicationID) {
            return base.Channel.DeleteUserFromPublication(out newToken, userID, token, userAuthorID, publicationID);
        }
    }
}
